name: "Gradle tests"
description: "Run Gradle tests with JDK + write a Job Summary + upload reports"

inputs:
  java-version:
    description: "Java version to use"
    required: false
    default: "17"
  distribution:
    description: "JDK distribution"
    required: false
    default: "temurin"
  gradle-args:
    description: "Arguments passed to Gradle"
    required: false
    default: "test"
  working-directory:
    description: "Directory where Gradle should be run"
    required: false
    default: "."
  upload-reports:
    description: "Upload test reports as GitHub artifact (true/false)"
    required: false
    default: "true"
  artifact-name:
    description: "Artifact name for uploaded reports"
    required: false
    default: "test-reports"

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Run Gradle
      id: gradle
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +e
        chmod +x ./gradlew
        ./gradlew ${{ inputs.gradle-args }}
        echo "exit_code=$?" >> "$GITHUB_OUTPUT"
        exit 0

    - name: Test summary
      if: always()
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +e

        chmod +x ./gradlew
        ./gradlew ${{ inputs.gradle-args }}
        EXIT_CODE=$?

        REPORT_DIR="build/test-results/test"
        HTML_REPORT="build/reports/tests/test/index.html"

        {
          echo "## Gradle tests"
          echo ""
          echo "- Command: \`./gradlew ${{ inputs.gradle-args }}\`"
          echo "- Java: \`${{ inputs.distribution }} ${{ inputs.java-version }}\`"
          echo "- Working dir: \`${{ inputs.working-directory }}\`"
          echo ""
          if [[ "$EXIT_CODE" == "0" ]]; then
            echo "✅ Result: **PASS**"
          else
            echo "❌ Result: **FAIL** (exit code: \`$EXIT_CODE\`)"
          fi
        } >> "$GITHUB_STEP_SUMMARY"

        # Optional: upload reports (works even if tests failed)
        if [[ "${{ inputs.upload-reports }}" == "true" ]]; then
          echo "Preparing artifact contents..." >/dev/null 2>&1
          # We can't call actions/upload-artifact from inside bash,
          # so we write a marker file for the workflow to upload.
          mkdir -p .github-test-artifacts
          rm -rf .github-test-artifacts/*
          if [[ -d "build/reports/tests" ]]; then cp -r build/reports/tests .github-test-artifacts/ 2>/dev/null; fi
          if [[ -d "build/test-results" ]]; then cp -r build/test-results .github-test-artifacts/ 2>/dev/null; fi

          {
            echo ""
            echo "### Test reports"
            echo "- Reports prepared in \`.github-test-artifacts/\` (uploaded by workflow step)"
          } >> "$GITHUB_STEP_SUMMARY"
        fi

        exit $EXIT_CODE

    - name: Upload test reports artifact
      if: ${{ always() && inputs.upload-reports == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ inputs.working-directory }}/build/reports/tests/**/*
          ${{ inputs.working-directory }}/build/test-results/**/*
        if-no-files-found: warn

    - name: Upload test reports artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-reports
        path: |
          build/reports/tests/**/*
          build/test-results/**/*
        if-no-files-found: warn