name: "Gradle tests"
description: "Run Gradle tests with JDK"

inputs:
  java-version:
    description: "Java version to use"
    required: false
    default: "17"
  distribution:
    description: "JDK distribution"
    required: false
    default: "temurin"
  gradle-args:
    description: "Arguments passed to Gradle"
    required: false
    default: "test"
  working-directory:
    description: "Directory where Gradle should be run"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Run Gradle
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        chmod +x ./gradlew
        ./gradlew ${{ inputs.gradle-args }}
