name: "Docker build and push"
description: "Build and push Docker image with Buildx"

inputs:
  context:
    required: false
    default: .
  file:
    required: false
    default: ./Dockerfile
  platforms:
    required: false
    default: linux/amd64,linux/arm64
  tags:
    required: true
  labels:
    required: false
    default: ""

outputs:
  digest:
    description: "Image digest"
    value: ${{ steps.push.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        driver-opts: |
          image=moby/buildkit:latest

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
